### ISSUE TITLE
Add Vue unit tests

### ISSUE THREAD

**Issue by mtlynch** [mtlynch/whatgotdone#279]
I'd love to have unit tests for the frontend, but I'm baffled by how to set up unit test infrastructure in Vue. I'd love some help getting that set up.

**Comment by Jeff-Duke** [comment]
@mtlynch I can pick this up if it's still available

**Comment by mtlynch** [comment]
Yes, that would be great!

**Comment by Jeff-Duke** [comment]
@mtlynch PR #308 open for this.

**Comment by Jeff-Duke** [comment]
PR #313 open for this. Happy Hacktoberfest! 🍂 🎃 👻 💀
