### ISSUE TITLE
Figure out a better way of serving static resources

### ISSUE THREAD

**Issue by mtlynch** [mtlynch/whatgotdone#292]
The [current implementation](https://github.com/mtlynch/whatgotdone/blob/7d9b38dd6421bb621e173f48222d1c28771d1ad8/backend/handlers/routes.go#L8-L21) can't possibly be the "right" way of doing it, but I can't figure out another implementation that works.

**Comment by SuliacLEGUILLOU** [comment]
Hey, I am from hacktoberfest o/

What about putting every  file into a `/statics` directory and serving it?
Would reduce declaration to something like:
```
s.router.PathPrefix("/js").Handler(fs)
	s.router.PathPrefix("/css").Handler(fs)
	s.router.PathPrefix("/images").Handler(fs)
	s.router.PathPrefix("/statics").Handler(fs)
```

**Comment by GrimTheReaper** [comment]
So, in my experiences a good way to deal with static files is with `http.FileSystem` instead of `http.FileServer`, and then as followed [here](https://gist.github.com/hauxe/f2ea1901216177ccf9550a1b8bd59178#file-http_static_correct-go). I'm writing it up in a PR, as well as other tidbits of fixes.

**Comment by mtlynch** [comment]
Cool, thanks! That plan sounds good to me. My only note is that I'd like to keep the `/favicon.ico` route working from the root path because it looks like not all applications know how to find it elsewhere.

**Comment by GrimTheReaper** [comment]
So, the example in the gist showed things from `/static`, but it wasn't very hard to modify it slightly to get it working from the root path, as everything should. Right now I'm running into issues testing (can't get gcp to behave on my connection) but I'll create a PR for later testing if you'd like to do that at your leisure.
