### ISSUE TITLE
Improve Configuration

### ISSUE THREAD

**Issue by GrimTheReaper** [mtlynch/whatgotdone#301]
A few parts of this application are hardcoded, such as the `./frontend/dist` location. This is very ridged and might push some people away who want to configure it to their needs. I recommend using environmental variables, and possibly a mix of flags.

**Comment by mtlynch** [comment]
Thanks @GrimTheReaper. Can you help me understand what issues are created by the hardcoded `./frontend/dist`?

I can see how it's a problem to hardcode something that exists outside of this repo, as different users may have different environments, but `./frontend/dist` will be the same path for anyone who uses this repo.

**Comment by GrimTheReaper** [comment]
I just have the general philosophy to never hardcode paths, as well as the system admin in me saying that anything being served should be in `/var/www`, although given how this looks to get deployed it's not that much of an issue. 

The main reason why I think it might be good idea to do this is that it just adds more flexibility to the users, if they want it. Better to have them and not use them, than need them and not have them.
