### ISSUE TITLE
Task list shouldn't show bullet points next to check box

### ISSUE THREAD

**Issue by goleary** [mtlynch/whatgotdone#434]
https://twitter.com/deliberatecoder/status/1225945347438108674

github:
![image](https://user-images.githubusercontent.com/16123225/74077868-5bcac380-49d8-11ea-99cd-072a0f3484d1.png)

wgd:
![image](https://user-images.githubusercontent.com/16123225/74077857-51a8c500-49d8-11ea-934a-c80b1941e75a.png)

**Comment by mtlynch** [comment]
What's the markdown that generates this?

**Comment by goleary** [comment]
`- [ ] item`

**Comment by rlorenzo** [comment]
Made a pull request here to fix this issue: https://github.com/mtlynch/whatgotdone/pull/535
