### ISSUE TITLE
Feature: export a user's entries

### ISSUE THREAD

**Issue by hirowatari** [mtlynch/whatgotdone#542]
I'm interested in being able to export all my journal entries.  I would be interested in creating this functionality myself if you would want it in the product.  I wanted to check in with you before I worked on it.

Thanks for creating `whatgotdone`.  I really enjoy using it.

**Comment by mtlynch** [comment]
Sure, that sounds like a great feature!

How would you like to expose the feature in the UI?

**Comment by hirowatari** [comment]
Great.  Initially I was thinking of putting it under Account->Profile or Preferences but it really feels a bit hamfisted in either place.  The other idea was to just to have it as a nav item under Account.  Does that seem reasonable?

**Comment by mtlynch** [comment]
Yeah, nav item sounds good to me.

**Comment by hirowatari** [comment]
Thanks a lot for doing this! 👍👍  Much appreciated.
