### ISSUE TITLE
Add support for posting last week's entry

### ISSUE THREAD

**Issue by WardBenjamin** [mtlynch/whatgotdone#792]
I had a partial entry saved in WhatGotDone for last week, and I was going to wrap it up and post this morning. 

I'd like to be able to:
- access that partial entry from last week
- post an entry backdated by at least 2-3 days (that way you can post until say Monday for the previous week)

**Comment by mtlynch** [comment]
Thanks for reporting this!

I'm currently tracking this in #318.

The workaround is to edit this week's entry and manually change the date in the URL to the week you want to edit.

**Comment by WardBenjamin** [comment]
Thanks, totally missed that!
